### ISSUE TITLE
Easy issue, no data back

### ISSUE THREAD

**Issue by iankf** [pavel-odintsov/fastnetmon#455]
Hi,

I run /opt/fastnetmon/fastnetmon_client but get 0 data back on everything, i suspect its something to do with netflow and the driver package.

Hyper-v virtual machine
Debian installed
Network connections all work
Followed this page 
https://github.com/FastVPSEestiOu/fastnetmon/blob/master/docs/NETMAP_INSTALL.md
but with 
./configure --kernel-sources=/usr/src/linux-3.2.68 --no-drivers

This was because all drivers failed install so hoped I could use the inbuilt ones

The host has server adapters of i350

**Comment by pavel-odintsov** [comment]
Hello!

Have you enabled promisc mode for netmap's interface with ifconfig ETHX promisc ?

**Comment by iankf** [comment]
Hello,

Yes I did this

**Comment by iankf** [comment]
![fastmon](https://cloud.githubusercontent.com/assets/15941614/11299298/8fd5d79c-8f7d-11e5-994f-4bd6cc0bb79d.gif)

If it helps, this is what I'm looking at

**Comment by pavel-odintsov** [comment]
Hello!

Unfortunately without patched drivers you could not use netmap. So you could use my custom prepared driver for this: https://github.com/pavel-odintsov/igb-linux-netmap. You could use automatic install script for this: https://gist.github.com/pavel-odintsov/6353bfd3bfd7dba2d99a

**Comment by iankf** [comment]
Hello,

Thanks for the auto script, so I ran the one you put on (https://gist.github.com/pavel-odintsov/6353bfd3bfd7dba2d99a )and then fastnetmon_install.pl

Everything seems to go through fine although I notice the netmap one (netmap_install.pl) does not include adding things into the start up of rc.local.

Anyway I ran ifconfig eth0 promisc just in case, nothing being picked up still though,, the log does not report any errors.

I'm testing this via pinging the server this is on but 0 on everything

**Comment by iankf** [comment]
Updating configuration file
# Netmap traffic capture (very fast but need patched drivers)
mirror_netmap = on

You get
[ERROR] Can't open netmap device netmap:eth0

**Comment by pavel-odintsov** [comment]
Could you share dmesg and lsmod output?

**Comment by iankf** [comment]
[dmesg.txt](https://github.com/pavel-odintsov/fastnetmon/files/41553/dmesg.txt)
[lsmod.txt](https://github.com/pavel-odintsov/fastnetmon/files/41552/lsmod.txt)

These are from after a reboot

**Comment by pavel-odintsov** [comment]
So you need to insert netmap module and patched netmap driver. I haven't saw any mentions about netmap in dmesg log. 

Just run igb and netmap with insmod command from /tmp folder.

**Comment by iankf** [comment]
My apologies, what commands exactly am I running?

insmod igb
insmod netmap

**Comment by pavel-odintsov** [comment]
When netmap_install.pl script finished if produces output: path to igb.ko and netmap.ko. So you should move this files to your custom folder, for example: /opt/netmap.

Than you need to add to rc.local:
```bash
rmmod igb
rmmod igb
insmod /opt/netmap/igb.ko
insmod /opt/netmap/netmap.ko
``` 

And run FastNetMon. So pleasee keep in mind if you are using igb for "management interface" it will go away in this case. Please be careful.

**Comment by iankf** [comment]
Running through it now, one thing I notice when running your script it used e1000e and not igb

**Comment by iankf** [comment]
Hi,

So edited the file to use igb
Also cloned the repo you mentioned so its igb-linux-netmap.

However on netmap_install.pl I get
Ign http://ftp.uk.debian.org jessie InRelease
Hit http://ftp.uk.debian.org jessie-updates InRelease
Hit http://security.debian.org jessie/updates InRelease
Hit http://ftp.uk.debian.org jessie Release.gpg
Hit http://ftp.uk.debian.org jessie Release
Hit http://ftp.uk.debian.org jessie-updates/main Sources
Get:1 http://ftp.uk.debian.org jessie-updates/main amd64 Packages/DiffIndex [367 B]
Hit http://ftp.uk.debian.org jessie-updates/main Translation-en
Hit http://security.debian.org jessie/updates/main Sources
Hit http://ftp.uk.debian.org jessie/main Sources
Hit http://ftp.uk.debian.org jessie/main amd64 Packages
Hit http://security.debian.org jessie/updates/main amd64 Packages
Hit http://ftp.uk.debian.org jessie/main Translation-en
Hit http://security.debian.org jessie/updates/main Translation-en
Fetched 367 B in 5s (66 B/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
gcc is already the newest version.
git is already the newest version.
make is already the newest version.
linux-headers-3.16.0-4-amd64 is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Cloning into 'igb-linux-netmap'...
remote: Counting objects: 55, done.
remote: Total 55 (delta 0), reused 0 (delta 0), pack-reused 55
Unpacking objects: 100% (55/55), done.
Checking connectivity... done.
Cloning into 'netmap'...
remote: Counting objects: 17303, done.
remote: Compressing objects: 100% (130/130), done.
remote: Total 17303 (delta 72), reused 0 (delta 0), pack-reused 17157
Receiving objects: 100% (17303/17303), 5.71 MiB | 3.62 MiB/s, done.
Resolving deltas: 100% (10888/10888), done.
Checking connectivity... done.
Note: checking out 'add1e50657e6861db791067804001307ebb5cf86'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at add1e50... Merge branch 'master' into github-master
********************************** WARNING **********************************
*** Cannot find full kernel sources. We assume that the drivers sources'
*** location has been provided in the override file.
*****************************************************************************
kernel directory            /lib/modules/3.16.0-4-amd64/build
                            [/usr/src/linux-headers-3.16.0-4-amd64]
linux version               31007  [3.16.7]
module file                 netmap.ko
subsystems                  generic monitor pipe vale
kernel sources              /lib/modules/3.16.0-4-amd64/build
                            [/usr/src/linux-headers-3.16.0-4-amd64]
requested drivers           igb

Contents of the drivers.mak file:

  Note: only drivers for which both the <driver>-src and the
  <driver>-patch variable are set may be used in native mode (assuming
  we can actually patch the sources). Other NICs will be accessed using
  the generic driver, at reduced performance.

########################################
#  configure generated values          #
########################################
igb-src :=
igb-patch := patches/diff--igb--30f00--40100
igb-dst := igb
########################################
# ovverride from
# igb-override
########################################
igb-dst := igb
igb-patch := #(leave empty)
igb-src := /tmp/netmap_build_tmp_folder.JeA7v0ohAZ/igb-linux-netmap/igb-5.3.3.2/src/
cp -Rp /tmp/netmap_build_tmp_folder.JeA7v0ohAZ/igb-linux-netmap/igb-5.3.3.2/src/ igb
mv igb/Makefile igb/orig.mak || mv igb/Kbuild igb/orig.mak; cp drv-subdir.mak igb/Makefile
touch get-igb
make -C /lib/modules/3.16.0-4-amd64/build M=/tmp/netmap_build_tmp_folder.JeA7v0ohAZ/netmap/LINUX EXTRA_CFLAGS='-I/tmp/netmap_build_tmp_folder.JeA7v0ohAZ/netmap/LINUX -I/tmp/netmap_build_tmp_folder.JeA7v0ohAZ/netmap/LINUX -I/tmp/netmap_build_tmp_folder.JeA7v0ohAZ/netmap/LINUX/../sys -I/tmp/netmap_build_tmp_folder.JeA7v0ohAZ/netmap/LINUX/../sys/dev -DCONFIG_NETMAP -Wno-unused-but-set-variable -DCONFIG_NETMAP_GENERIC -DCONFIG_NETMAP_MONITOR -DCONFIG_NETMAP_PIPE -DCONFIG_NETMAP_VALE'  modules CONFIG_NETMAP=m CONFIG_IGB=m  O_DRIVERS="igb/" \
        NETMAP_DRIVER_SUFFIX=
make[1]: Entering directory '/usr/src/linux-headers-3.16.0-4-amd64'
Makefile:10: *** mixed implicit and normal rules: deprecated syntax
make[1]: Entering directory `/usr/src/linux-headers-3.16.0-4-amd64'
  CC [M]  /tmp/netmap_build_tmp_folder.JeA7v0ohAZ/netmap/LINUX/netmap_mem2.o
  CC [M]  /tmp/netmap_build_tmp_folder.JeA7v0ohAZ/netmap/LINUX/netmap_mbq.o
  CC [M]  /tmp/netmap_build_tmp_folder.JeA7v0ohAZ/netmap/LINUX/netmap_vale.o
  CC [M]  /tmp/netmap_build_tmp_folder.JeA7v0ohAZ/netmap/LINUX/netmap_offloadings.o
  CC [M]  /tmp/netmap_build_tmp_folder.JeA7v0ohAZ/netmap/LINUX/netmap_pipe.o
  CC [M]  /tmp/netmap_build_tmp_folder.JeA7v0ohAZ/netmap/LINUX/netmap_monitor.o
  CC [M]  /tmp/netmap_build_tmp_folder.JeA7v0ohAZ/netmap/LINUX/netmap_generic.o
  CC [M]  /tmp/netmap_build_tmp_folder.JeA7v0ohAZ/netmap/LINUX/netmap_common.o
  CC [M]  /tmp/netmap_build_tmp_folder.JeA7v0ohAZ/netmap/LINUX/netmap_linux.o
  LD [M]  /tmp/netmap_build_tmp_folder.JeA7v0ohAZ/netmap/LINUX/netmap.o
  CC [M]  /tmp/netmap_build_tmp_folder.JeA7v0ohAZ/netmap/LINUX/igb/igb_main.o
In file included from /tmp/netmap_build_tmp_folder.JeA7v0ohAZ/netmap/LINUX/igb/igb_main.c:324:0:
/tmp/netmap_build_tmp_folder.JeA7v0ohAZ/netmap/LINUX/if_igb_netmap.h: In function ‘igb_netmap_txsync’:
/tmp/netmap_build_tmp_folder.JeA7v0ohAZ/netmap/LINUX/if_igb_netmap.h:51:35: error: implicit declaration of function ‘rd32’ [-Werror=implicit-function-declaration]
 #define READ_TDH(_txr)   ({struct e1000_hw *hw = &adapter->hw;rd32(E1000_TDH((_txr)->reg_idx));} )
                                   ^
/tmp/netmap_build_tmp_folder.JeA7v0ohAZ/netmap/LINUX/if_igb_netmap.h:178:11: note: in expansion of macro ‘READ_TDH’
   nic_i = READ_TDH(txr);
           ^
/tmp/netmap_build_tmp_folder.JeA7v0ohAZ/netmap/LINUX/if_igb_netmap.h:51:45: warning: unused variable ‘hw’ [-Wunused-variable]
 #define READ_TDH(_txr)   ({struct e1000_hw *hw = &adapter->hw;rd32(E1000_TDH((_txr)->reg_idx));} )
                                             ^
/tmp/netmap_build_tmp_folder.JeA7v0ohAZ/netmap/LINUX/if_igb_netmap.h:178:11: note: in expansion of macro ‘READ_TDH’
   nic_i = READ_TDH(txr);
           ^
cc1: some warnings being treated as errors
/usr/src/linux-headers-3.16.0-4-common/scripts/Makefile.build:262: recipe for target '/tmp/netmap_build_tmp_folder.JeA7v0ohAZ/netmap/LINUX/igb/igb_main.o' failed
make[5]: *** [/tmp/netmap_build_tmp_folder.JeA7v0ohAZ/netmap/LINUX/igb/igb_main.o] Error 1
/usr/src/linux-headers-3.16.0-4-common/scripts/Makefile.build:409: recipe for target '/tmp/netmap_build_tmp_folder.JeA7v0ohAZ/netmap/LINUX/igb' failed
make[4]: *** [/tmp/netmap_build_tmp_folder.JeA7v0ohAZ/netmap/LINUX/igb] Error 2
/usr/src/linux-headers-3.16.0-4-common/Makefile:1350: recipe for target '_module_/tmp/netmap_build_tmp_folder.JeA7v0ohAZ/netmap/LINUX' failed
make[3]: *** [_module_/tmp/netmap_build_tmp_folder.JeA7v0ohAZ/netmap/LINUX] Error 2
Makefile:181: recipe for target 'sub-make' failed
make[2]: *** [sub-make] Error 2
Makefile:8: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-3.16.0-4-amd64'
netmap.mak:52: recipe for target 'all' failed
make: *** [all] Error 2
Could not make project

**Comment by pavel-odintsov** [comment]
Could you try to install raw igb driver from sourceforge? Looks like they have broken their build...

**Comment by pavel-odintsov** [comment]
I could recommend you to change kernel version or distribution to something stable. Because in other case folks from netmap or Intel could not help you with this bugs.

**Comment by iankf** [comment]
Hi,

So the latest driver does not work, going to look into the kernal version, I get the follow
Ign http://ftp.uk.debian.org jessie InRelease
Hit http://ftp.uk.debian.org jessie-updates InRelease
Hit http://security.debian.org jessie/updates InRelease
Hit http://ftp.uk.debian.org jessie Release.gpg
Hit http://ftp.uk.debian.org jessie Release
Hit http://ftp.uk.debian.org jessie-updates/main Sources
Get:1 http://ftp.uk.debian.org jessie-updates/main amd64 Packages/DiffIndex [367 B]
Hit http://ftp.uk.debian.org jessie-updates/main Translation-en
Hit http://security.debian.org jessie/updates/main Sources
Hit http://ftp.uk.debian.org jessie/main Sources
Hit http://ftp.uk.debian.org jessie/main amd64 Packages
Hit http://ftp.uk.debian.org jessie/main Translation-en
Hit http://security.debian.org jessie/updates/main amd64 Packages
Hit http://security.debian.org jessie/updates/main Translation-en
Fetched 367 B in 3s (103 B/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
gcc is already the newest version.
git is already the newest version.
make is already the newest version.
linux-headers-3.16.0-4-amd64 is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Cloning into 'igb-linux-netmap'...
remote: Counting objects: 55, done.
remote: Total 55 (delta 0), reused 0 (delta 0), pack-reused 55
Unpacking objects: 100% (55/55), done.
Checking connectivity... done.
Cloning into 'netmap'...
remote: Counting objects: 17303, done.
remote: Compressing objects: 100% (130/130), done.
remote: Total 17303 (delta 72), reused 0 (delta 0), pack-reused 17157
Receiving objects: 100% (17303/17303), 5.71 MiB | 3.19 MiB/s, done.
Resolving deltas: 100% (10888/10888), done.
Checking connectivity... done.
Note: checking out 'add1e50657e6861db791067804001307ebb5cf86'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at add1e50... Merge branch 'master' into github-master
********************************** WARNING **********************************
*** Cannot find full kernel sources. We assume that the drivers sources'
*** location has been provided in the override file.
*****************************************************************************
kernel directory            /lib/modules/3.16.0-4-amd64/build
                            [/usr/src/linux-headers-3.16.0-4-amd64]
linux version               31007  [3.16.7]
module file                 netmap.ko
subsystems                  generic monitor pipe vale
kernel sources              /lib/modules/3.16.0-4-amd64/build
                            [/usr/src/linux-headers-3.16.0-4-amd64]
requested drivers           igb

Contents of the drivers.mak file:

  Note: only drivers for which both the <driver>-src and the
  <driver>-patch variable are set may be used in native mode (assuming
  we can actually patch the sources). Other NICs will be accessed using
  the generic driver, at reduced performance.

########################################
#  configure generated values          #
########################################
igb-src :=
igb-patch := patches/diff--igb--30f00--40100
igb-dst := igb
########################################
# ovverride from
# igb-override
########################################
igb-dst := igb
igb-patch := #(leave empty)
igb-src := /tmp/netmap_build_tmp_folder.HpI2Wrsr1z/igb-linux-netmap/igb-5.3.3.2/src/
cp -Rp /tmp/netmap_build_tmp_folder.HpI2Wrsr1z/igb-linux-netmap/igb-5.3.3.2/src/ igb
mv igb/Makefile igb/orig.mak || mv igb/Kbuild igb/orig.mak; cp drv-subdir.mak igb/Makefile
touch get-igb
make -C /lib/modules/3.16.0-4-amd64/build M=/tmp/netmap_build_tmp_folder.HpI2Wrsr1z/netmap/LINUX EXTRA_CFLAGS='-I/tmp/netmap_build_tmp_folder.HpI2Wrsr1z/netmap/LINUX -I/tmp/netmap_build_tmp_folder.HpI2Wrsr1z/netmap/LINUX -I/tmp/netmap_build_tmp_folder.HpI2Wrsr1z/netmap/LINUX/../sys -I/tmp/netmap_build_tmp_folder.HpI2Wrsr1z/netmap/LINUX/../sys/dev -DCONFIG_NETMAP -Wno-unused-but-set-variable -DCONFIG_NETMAP_GENERIC -DCONFIG_NETMAP_MONITOR -DCONFIG_NETMAP_PIPE -DCONFIG_NETMAP_VALE'  modules CONFIG_NETMAP=m CONFIG_IGB=m  O_DRIVERS="igb/" \
        NETMAP_DRIVER_SUFFIX=
make[1]: Entering directory '/usr/src/linux-headers-3.16.0-4-amd64'
Makefile:10: *** mixed implicit and normal rules: deprecated syntax
make[1]: Entering directory `/usr/src/linux-headers-3.16.0-4-amd64'
  CC [M]  /tmp/netmap_build_tmp_folder.HpI2Wrsr1z/netmap/LINUX/netmap_mem2.o
  CC [M]  /tmp/netmap_build_tmp_folder.HpI2Wrsr1z/netmap/LINUX/netmap_mbq.o
  CC [M]  /tmp/netmap_build_tmp_folder.HpI2Wrsr1z/netmap/LINUX/netmap_vale.o
  CC [M]  /tmp/netmap_build_tmp_folder.HpI2Wrsr1z/netmap/LINUX/netmap_offloadings.o
  CC [M]  /tmp/netmap_build_tmp_folder.HpI2Wrsr1z/netmap/LINUX/netmap_pipe.o
  CC [M]  /tmp/netmap_build_tmp_folder.HpI2Wrsr1z/netmap/LINUX/netmap_monitor.o
  CC [M]  /tmp/netmap_build_tmp_folder.HpI2Wrsr1z/netmap/LINUX/netmap_generic.o
  CC [M]  /tmp/netmap_build_tmp_folder.HpI2Wrsr1z/netmap/LINUX/netmap_common.o
  CC [M]  /tmp/netmap_build_tmp_folder.HpI2Wrsr1z/netmap/LINUX/netmap_linux.o
  LD [M]  /tmp/netmap_build_tmp_folder.HpI2Wrsr1z/netmap/LINUX/netmap.o
  CC [M]  /tmp/netmap_build_tmp_folder.HpI2Wrsr1z/netmap/LINUX/igb/igb_main.o
In file included from /tmp/netmap_build_tmp_folder.HpI2Wrsr1z/netmap/LINUX/igb/igb_main.c:324:0:
/tmp/netmap_build_tmp_folder.HpI2Wrsr1z/netmap/LINUX/if_igb_netmap.h: In function ‘igb_netmap_txsync’:
/tmp/netmap_build_tmp_folder.HpI2Wrsr1z/netmap/LINUX/if_igb_netmap.h:51:35: error: implicit declaration of function ‘rd32’ [-Werror=implicit-function-declaration]
 #define READ_TDH(_txr)   ({struct e1000_hw *hw = &adapter->hw;rd32(E1000_TDH((_txr)->reg_idx));} )
                                   ^
/tmp/netmap_build_tmp_folder.HpI2Wrsr1z/netmap/LINUX/if_igb_netmap.h:178:11: note: in expansion of macro ‘READ_TDH’
   nic_i = READ_TDH(txr);
           ^
/tmp/netmap_build_tmp_folder.HpI2Wrsr1z/netmap/LINUX/if_igb_netmap.h:51:45: warning: unused variable ‘hw’ [-Wunused-variable]
 #define READ_TDH(_txr)   ({struct e1000_hw *hw = &adapter->hw;rd32(E1000_TDH((_txr)->reg_idx));} )
                                             ^
/tmp/netmap_build_tmp_folder.HpI2Wrsr1z/netmap/LINUX/if_igb_netmap.h:178:11: note: in expansion of macro ‘READ_TDH’
   nic_i = READ_TDH(txr);
           ^
cc1: some warnings being treated as errors
/usr/src/linux-headers-3.16.0-4-common/scripts/Makefile.build:262: recipe for target '/tmp/netmap_build_tmp_folder.HpI2Wrsr1z/netmap/LINUX/igb/igb_main.o' failed
make[5]: *** [/tmp/netmap_build_tmp_folder.HpI2Wrsr1z/netmap/LINUX/igb/igb_main.o] Error 1
/usr/src/linux-headers-3.16.0-4-common/scripts/Makefile.build:409: recipe for target '/tmp/netmap_build_tmp_folder.HpI2Wrsr1z/netmap/LINUX/igb' failed
make[4]: *** [/tmp/netmap_build_tmp_folder.HpI2Wrsr1z/netmap/LINUX/igb] Error 2
/usr/src/linux-headers-3.16.0-4-common/Makefile:1350: recipe for target '_module_/tmp/netmap_build_tmp_folder.HpI2Wrsr1z/netmap/LINUX' failed
make[3]: *** [_module_/tmp/netmap_build_tmp_folder.HpI2Wrsr1z/netmap/LINUX] Error 2
Makefile:181: recipe for target 'sub-make' failed
make[2]: *** [sub-make] Error 2
Makefile:8: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-3.16.0-4-amd64'
netmap.mak:52: recipe for target 'all' failed
make: *** [all] Error 2
Could not make project

**Comment by pavel-odintsov** [comment]
Hello!

Very strange. Unfortunately I have not idea about this.

I could recommend to switch to Debian 8 or Ubutnu 14.0. They have awesome support from netmap and tested vert deeply.

You could try PF_RING ZC instead but it need license for ~200 euro per 10GE.

**Comment by iankf** [comment]
Hi,

I am running Debian 8 I'm afraid. maybe I should try ubuntu

**Comment by pavel-odintsov** [comment]
Ah, very interesing. Debian 8 should work perfectly. I'm using it as my development platform.

**Comment by iankf** [comment]
Are you using it on bare bones or through a hyper visor?

**Comment by pavel-odintsov** [comment]
bare bone

**Comment by pavel-odintsov** [comment]
I will try to build igb driver in my test env in next 2 days. Could you wait? Please poke me in case of delay :)

**Comment by iankf** [comment]
Maybe because I'm using Hyper-V 2012 R2, the SR-IOV is not being passed through. I have a machine bare bones for linux. Will take me about three days to prep so no problem

**Comment by pavel-odintsov** [comment]
It depends in used cpu and platform. I have experience with passthrought and very often it works really BAD. I have some information about Xeon e5 v3 with supermicro palatform. It works perfectly in this mode. But older cpus work really bad...

**Comment by iankf** [comment]
Ok so did a linux install on metal, same results with igb with error. Did the e1000e option but no results displayed, the adapter in use in the proof of concept is Intel(R) Ethernet Server Adapter I350-T4 if thats the problem, we cannot take this to production until it passes through this environment.

**Comment by pavel-odintsov** [comment]
I have built igb patched driver, you could try it: https://github.com/pavel-odintsov/igb-linux-netmap

**Comment by Anito23** [comment]
To remove the following error while compile igb driver:

In file included from /tmp/netmap_build_tmp_folder.JeA7v0ohAZ/netmap/LINUX/igb/igb_main.c:324:0:
/tmp/netmap_build_tmp_folder.JeA7v0ohAZ/netmap/LINUX/if_igb_netmap.h: In function ‘igb_netmap_txsync’:
/tmp/netmap_build_tmp_folder.JeA7v0ohAZ/netmap/LINUX/if_igb_netmap.h:51:35: error: implicit declaration of function ‘rd32’ [-Werror=implicit-function-declaration]

Need to change one line in file ./netmap/LINUX/if_igb_netmap.h

from

#define READ_TDH(_txr)                  ({struct e1000_hw *hw = &adapter->hw;rd32(E1000_TDH((_txr)->reg_idx));} )

to

#define READ_TDH(_txr)                  ({struct e1000_hw *hw = &adapter->hw;E1000_READ_REG(hw,E1000_TDH((_txr)->reg_idx));} )

Then igb driver compile without errors.

**Comment by pavel-odintsov** [comment]
You could use my drivers with patches;)

On Wednesday, 22 June 2016, Anito23 <notifications@github.com> wrote:

> To remove the following error while compile igb driver:
>
> In file included from
> /tmp/netmap_build_tmp_folder.JeA7v0ohAZ/netmap/LINUX/igb/igb_main.c:324:0:
> /tmp/netmap_build_tmp_folder.JeA7v0ohAZ/netmap/LINUX/if_igb_netmap.h: In
> function ‘igb_netmap_txsync’:
> /tmp/netmap_build_tmp_folder.JeA7v0ohAZ/netmap/LINUX/if_igb_netmap.h:51:35:
> error: implicit declaration of function ‘rd32’
> [-Werror=implicit-function-declaration]
>
> Need to change one line in file ./netmap/LINUX/if_igb_netmap.h
>
> from
>
> #define READ_TDH(_txr) ({struct e1000_hw *hw =
> &adapter->hw;rd32(E1000_TDH((_txr)->reg_idx));} )
>
> to
>
> #define READ_TDH(_txr) ({struct e1000_hw *hw =
> &adapter->hw;E1000_READ_REG(hw,E1000_TDH((_txr)->reg_idx));} )
>
> Then igb driver compile without errors.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/pavel-odintsov/fastnetmon/issues/455#issuecomment-227793978>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACnfZlDwFO6cresrOjpeA8xgBGTnXgEMks5qOV4hgaJpZM4GmTxH>
> .
>


-- 
Sincerely yours, Pavel Odintsov

**Comment by pavel-odintsov** [comment]
https://github.com/pavel-odintsov/igb-linux-netmap

On Wednesday, 22 June 2016, Pavel Odintsov <pavel.odintsov@gmail.com> wrote:

> You could use my drivers with patches;)
>
> On Wednesday, 22 June 2016, Anito23 <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> To remove the following error while compile igb driver:
>>
>> In file included from
>> /tmp/netmap_build_tmp_folder.JeA7v0ohAZ/netmap/LINUX/igb/igb_main.c:324:0:
>> /tmp/netmap_build_tmp_folder.JeA7v0ohAZ/netmap/LINUX/if_igb_netmap.h: In
>> function ‘igb_netmap_txsync’:
>> /tmp/netmap_build_tmp_folder.JeA7v0ohAZ/netmap/LINUX/if_igb_netmap.h:51:35:
>> error: implicit declaration of function ‘rd32’
>> [-Werror=implicit-function-declaration]
>>
>> Need to change one line in file ./netmap/LINUX/if_igb_netmap.h
>>
>> from
>>
>> #define READ_TDH(_txr) ({struct e1000_hw *hw =
>> &adapter->hw;rd32(E1000_TDH((_txr)->reg_idx));} )
>>
>> to
>>
>> #define READ_TDH(_txr) ({struct e1000_hw *hw =
>> &adapter->hw;E1000_READ_REG(hw,E1000_TDH((_txr)->reg_idx));} )
>>
>> Then igb driver compile without errors.
>>
>> —
>> You are receiving this because you modified the open/close state.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/pavel-odintsov/fastnetmon/issues/455#issuecomment-227793978>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/ACnfZlDwFO6cresrOjpeA8xgBGTnXgEMks5qOV4hgaJpZM4GmTxH>
>> .
>>
>
>
> --
> Sincerely yours, Pavel Odintsov
>


-- 
Sincerely yours, Pavel Odintsov

**Comment by pavel-odintsov** [comment]
But please be careful. Any kernel more recent than 3.19 will not work this
way. And I do not know why.

On Wednesday, 22 June 2016, Pavel Odintsov <pavel.odintsov@gmail.com> wrote:

> https://github.com/pavel-odintsov/igb-linux-netmap
>
> On Wednesday, 22 June 2016, Pavel Odintsov <pavel.odintsov@gmail.com
> <javascript:_e(%7B%7D,'cvml','pavel.odintsov@gmail.com');>> wrote:
>
>> You could use my drivers with patches;)
>>
>> On Wednesday, 22 June 2016, Anito23 <notifications@github.com> wrote:
>>
>>> To remove the following error while compile igb driver:
>>>
>>> In file included from
>>> /tmp/netmap_build_tmp_folder.JeA7v0ohAZ/netmap/LINUX/igb/igb_main.c:324:0:
>>> /tmp/netmap_build_tmp_folder.JeA7v0ohAZ/netmap/LINUX/if_igb_netmap.h: In
>>> function ‘igb_netmap_txsync’:
>>> /tmp/netmap_build_tmp_folder.JeA7v0ohAZ/netmap/LINUX/if_igb_netmap.h:51:35:
>>> error: implicit declaration of function ‘rd32’
>>> [-Werror=implicit-function-declaration]
>>>
>>> Need to change one line in file ./netmap/LINUX/if_igb_netmap.h
>>>
>>> from
>>>
>>> #define READ_TDH(_txr) ({struct e1000_hw *hw =
>>> &adapter->hw;rd32(E1000_TDH((_txr)->reg_idx));} )
>>>
>>> to
>>>
>>> #define READ_TDH(_txr) ({struct e1000_hw *hw =
>>> &adapter->hw;E1000_READ_REG(hw,E1000_TDH((_txr)->reg_idx));} )
>>>
>>> Then igb driver compile without errors.
>>>
>>> —
>>> You are receiving this because you modified the open/close state.
>>> Reply to this email directly, view it on GitHub
>>> <https://github.com/pavel-odintsov/fastnetmon/issues/455#issuecomment-227793978>,
>>> or mute the thread
>>> <https://github.com/notifications/unsubscribe/ACnfZlDwFO6cresrOjpeA8xgBGTnXgEMks5qOV4hgaJpZM4GmTxH>
>>> .
>>>
>>
>>
>> --
>> Sincerely yours, Pavel Odintsov
>>
>
>
> --
> Sincerely yours, Pavel Odintsov
>


-- 
Sincerely yours, Pavel Odintsov

**Comment by Anito23** [comment]
Error was at the time of compiling your drivers with patches from link https://github.com/pavel-odintsov/igb-linux-netmap.

I find that raw igb driver from sourceforge have different name of cod block. In raw igb the name is "e1000_read_reg" but in drivers from source code of kernel 3.16 same cod have name "igb_rd32". The code in this block is absolutely the same http://pastebin.com/raw/QYG3Vu0i. For this reason, any raw igb drivers from sourceforge (also with your patches) compile with error on Debian 8 with kernel 3.16:

/tmp/netmap_build_tmp_folder.JeA7v0ohAZ/netmap/LINUX/if_igb_netmap.h:51:35: error: implicit declaration of function ‘rd32’ [-Werror=implicit-function-declaration]

**Comment by pavel-odintsov** [comment]
а, понял...

On Thu, Jun 23, 2016 at 12:09 AM, Anito23 <notifications@github.com> wrote:

> Error was at the time of compiling your drivers with patches from link
> https://github.com/pavel-odintsov/igb-linux-netmap.
>
> I find that raw igb driver from sourceforge have different name of cod
> block. In raw igb the name is "e1000_read_reg" but in drivers from source
> code of kernel 3.16 same cod have name "igb_rd32". The code in this block
> is absolutely the same http://pastebin.com/raw/QYG3Vu0i. For this reason,
> any raw igb drivers from sourceforge (also with your patches) compile with
> error on Debian 8 with kernel 3.16:
>
> /tmp/netmap_build_tmp_folder.JeA7v0ohAZ/netmap/LINUX/if_igb_netmap.h:51:35:
> error: implicit declaration of function ‘rd32’
> [-Werror=implicit-function-declaration]
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/pavel-odintsov/fastnetmon/issues/455#issuecomment-227968040>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACnfZsFq9_9wPCzN2sbbSKeHkpIbF28Dks5qOjE0gaJpZM4GmTxH>
> .
>



-- 
Sincerely yours, Pavel Odintsov
