### ISSUE TITLE
fastnetmon fails to build with libndpi-dev 2.2-1

### ISSUE THREAD

**Issue by bdrung** [pavel-odintsov/fastnetmon#699]
fastnetmon fails to build from source with libndpi-dev 2.2-1 on Debian unstable:
```
...
/usr/bin/c++  -DENABLE_DPI -DENABLE_LUA_HOOKS -DFASTNETMON_ENABLE_AFPACKET -DMONGO -DNETMAP_PLUGIN -DREDIS -I/usr/include/libndpi-2.2.0 -I/usr/include/luajit-2.1 -I/build/1st/fastnetmon-1.1.3+dfsg/src/netmap_plugin/netmap_includes -I/usr/include/libmongoc-1.0 -I/usr/include/libbson-1.0  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2   -o CMakeFiles/fastnetmon.dir/fastnetmon.cpp.o -c /build/1st/fastnetmon-1.1.3+dfsg/src/fastnetmon.cpp
/build/1st/fastnetmon-1.1.3+dfsg/src/fastnetmon.cpp: In function 'void produce_dpi_dump_for_pcap_dump(std::__cxx11::string, std::stringstream&, std::__cxx11::string)':
/build/1st/fastnetmon-1.1.3+dfsg/src/fastnetmon.cpp:3635:85: error: 'ndpi_protocol {aka struct ndpi_proto}' has no member named 'protocol'; did you mean 'app_protocol'?
         char* protocol_name = ndpi_get_proto_name(my_ndpi_struct, detected_protocol.protocol);
                                                                                     ^~~~~~~~
                                                                                     app_protocol
/build/1st/fastnetmon-1.1.3+dfsg/src/fastnetmon.cpp:3638:31: error: 'ndpi_protocol {aka struct ndpi_proto}' has no member named 'protocol'; did you mean 'app_protocol'?
         if (detected_protocol.protocol == NDPI_PROTOCOL_DNS) {
                               ^~~~~~~~
                               app_protocol
/build/1st/fastnetmon-1.1.3+dfsg/src/fastnetmon.cpp:3644:38: error: 'ndpi_protocol {aka struct ndpi_proto}' has no member named 'protocol'; did you mean 'app_protocol'?
         } else if (detected_protocol.protocol == NDPI_PROTOCOL_NTP) {
                                      ^~~~~~~~
                                      app_protocol
/build/1st/fastnetmon-1.1.3+dfsg/src/fastnetmon.cpp:3649:38: error: 'ndpi_protocol {aka struct ndpi_proto}' has no member named 'protocol'; did you mean 'app_protocol'?
         } else if (detected_protocol.protocol == NDPI_PROTOCOL_SSDP) {
                                      ^~~~~~~~
                                      app_protocol
/build/1st/fastnetmon-1.1.3+dfsg/src/fastnetmon.cpp:3652:38: error: 'ndpi_protocol {aka struct ndpi_proto}' has no member named 'protocol'; did you mean 'app_protocol'?
         } else if (detected_protocol.protocol == NDPI_PROTOCOL_SNMP) {
                                      ^~~~~~~~
                                      app_protocol
CMakeFiles/fastnetmon.dir/build.make:65: recipe for target 'CMakeFiles/fastnetmon.dir/fastnetmon.cpp.o' failed
make[3]: *** [CMakeFiles/fastnetmon.dir/fastnetmon.cpp.o] Error 1
```
This bug was reported to Debian: https://bugs.debian.org/887623

**Comment by pavel-odintsov** [comment]
Hello!

Oh, they did it again. API is broken ;(

Fortunately, they recently introduced option to create ifdefs about this case: https://github.com/ntop/nDPI/commit/22beb7714d2a78d4a57a4cf78cf8da7102e549e3

Probably, they changed API here https://github.com/ntop/nDPI/commit/5de6a96af5754c13846883b556f58fc79831c61d 

Could you apply patch with ifdef to change field names after this version?
