### PR TITLE
Support nDPI 2.2

### LINKED ISSUE #699: fastnetmon fails to build with libndpi-dev 2.2-1
fastnetmon fails to build from source with libndpi-dev 2.2-1 on Debian unstable:
```
...
/usr/bin/c++  -DENABLE_DPI -DENABLE_LUA_HOOKS -DFASTNETMON_ENABLE_AFPACKET -DMONGO -DNETMAP_PLUGIN -DREDIS -I/usr/include/libndpi-2.2.0 -I/usr/include/luajit-2.1 -I/build/1st/fastnetmon-1.1.3+dfsg/src/netmap_plugin/netmap_includes -I/usr/include/libmongoc-1.0 -I/usr/include/libbson-1.0  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2   -o CMakeFiles/fastnetmon.dir/fastnetmon.cpp.o -c /build/1st/fastnetmon-1.1.3+dfsg/src/fastnetmon.cpp
/build/1st/fastnetmon-1.1.3+dfsg/src/fastnetmon.cpp: In function 'void produce_dpi_dump_for_pcap_dump(std::__cxx11::string, std::stringstream&, std::__cxx11::string)':
/build/1st/fastnetmon-1.1.3+dfsg/src/fastnetmon.cpp:3635:85: error: 'ndpi_protocol {aka struct ndpi_proto}' has no member named 'protocol'; did you mean 'app_protocol'?
         char* protocol_name = ndpi_get_proto_name(my_ndpi_struct, detected_protocol.protocol);
                                                                                     ^~~~~~~~
                                                                                     app_protocol
/build/1st/fastnetmon-1.1.3+dfsg/src/fastnetmon.cpp:3638:31: error: 'ndpi_protocol {aka struct ndpi_proto}' has no member named 'protocol'; did you mean 'app_protocol'?
         if (detected_protocol.protocol == NDPI_PROTOCOL_DNS) {
                               ^~~~~~~~
                               app_protocol
/build/1st/fastnetmon-1.1.3+dfsg/src/fastnetmon.cpp:3644:38: error: 'ndpi_protocol {aka struct ndpi_proto}' has no member named 'protocol'; did you mean 'app_protocol'?
         } else if (detected_protocol.protocol == NDPI_PROTOCOL_NTP) {
                                      ^~~~~~~~
                                      app_protocol
/build/1st/fastnetmon-1.1.3+dfsg/src/fastnetmon.cpp:3649:38: error: 'ndpi_protocol {aka struct ndpi_proto}' has no member named 'protocol'; did you mean 'app_protocol'?
         } else if (detected_protocol.protocol == NDPI_PROTOCOL_SSDP) {
                                      ^~~~~~~~
                                      app_protocol
/build/1st/fastnetmon-1.1.3+dfsg/src/fastnetmon.cpp:3652:38: error: 'ndpi_protocol {aka struct ndpi_proto}' has no member named 'protocol'; did you mean 'app_protocol'?
         } else if (detected_protocol.protocol == NDPI_PROTOCOL_SNMP) {
                                      ^~~~~~~~
                                      app_protocol
CMakeFiles/fastnetmon.dir/build.make:65: recipe for target 'CMakeFiles/fastnetmon.dir/fastnetmon.cpp.o' failed
make[3]: *** [CMakeFiles/fastnetmon.dir/fastnetmon.cpp.o] Error 1
```
This bug was reported to Debian: https://bugs.debian.org/887623

### PR DESCRIPTION
**Pull request by bdrung**
nDPI 2.0 renamed detected_protocol.protocol to detected_protocol.app_protocol (to avoid confusion). This fixes #699.

### CODE REVIEW

**Comment by pavel-odintsov** [comment]
Nice! Thank you!
