### ISSUE TITLE
Add support for Boost 1.87.0 (Boost.Asio removals)

### ISSUE THREAD

**Issue by cho-m** [pavel-odintsov/fastnetmon#1027]
> * Your operating system name and version? 

Tested on Homebrew CI so macOS 13-15 and Linux Ubuntu 22.04

> * Please attach your /etc/fastnetmon.conf configuration file
> * What capture engine are you using: Netflow, sFlow, miror?
> * If you are using Netflow or sFlow, please specify version, vendor name, model name and firmware of agent device.  
> * Please attach /var/log/fastnetmon.log

N/A as related to compilation rather than running.

---

Advance notice that FastNetMon does not compile with upcoming Boost 1.87.0 (based on beta1) as Boost.Asio has removed the deprecated io_service https://github.com/boostorg/asio/commit/ec0908c562102915423d8bd7aefd3079efbb6c86

This causes errors like:
```
fastnetmon-1.2.7/src/fast_library.cpp:1090:22: error: no type named 'io_service' in namespace 'boost::asio'
 1090 |         boost::asio::io_service io_service;
      |         ~~~~~~~~~~~~~^
```

Also need to remove `boost::asio::ip::tcp::resolver::query` and change code as described in https://www.boost.org/doc/libs/1_86_0/doc/html/boost_asio/net_ts.html 
https://github.com/pavel-odintsov/fastnetmon/blob/a813f7da8376b777ad9c38d8789dd57da7612b8f/src/fast_library.cpp#L1097-L1102

Easiest option is to require a minimum of Boost 1.66.0 (https://github.com/boostorg/asio/commit/b60e92b13ef68dfbb9af180d76eae41d22e19356) and update APIs, which may be possible as code already uses `io_context`:
https://github.com/pavel-odintsov/fastnetmon/blob/a813f7da8376b777ad9c38d8789dd57da7612b8f/src/fast_library.cpp#L1520

**Comment by pavel-odintsov** [comment]
Hello!

Thank you very much for reporting this issue! I'll look on it shortly

**Comment by pavel-odintsov** [comment]
Marek Zarychta prepared patch for it
